from datetime import datetime, timedelta, timezone

# Centralized configuration file controlling dataset scale and realism.

DB_PATH = "output/asana_simulation.sqlite"

# ORGANISATION CONFIGURATION
ORG_COUNT = 1
ORG_MIN_AGE_YEARS = 3
ORG_MAX_AGE_YEARS = 5

# TEAMS CONFIGURATION
MIN_TEAMS = 20
MAX_TEAMS = 40

# USERS CONFIGURATION 
MIN_USERS = 5000
MAX_USERS = 10000

MAX_TEAMS_PER_USER = 3

# PROJECTS CONFIGURATION
MIN_PROJECTS_PER_TEAM = 5
MAX_PROJECTS_PER_TEAM = 15

# TASKS CONFIGURATION
MIN_TASKS_PER_PROJECT = 30
MAX_TASKS_PER_PROJECT = 150

UNASSIGNED_TASK_PROBABILITY = 0.15

# DATE RANGES
NOW = datetime.now(timezone.utc)

PROJECT_LOOKBACK_DAYS = 365
TASK_LOOKBACK_DAYS = 180

# COMMENTS
MAX_COMMENTS_PER_TASK = 8

# SUBTASK BEHAVIOUR
SUBTASK_PROBABILITY = 0.4
MAX_SUBTASKS_PER_TASK = 6
